/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_forms;

/**
 *
 * @author Matt
 */
public class CustomerServiceFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerServiceFrame
     */
    public CustomerServiceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_A = new javax.swing.JPanel();
        lblFirstName_A = new javax.swing.JLabel();
        lblLastName_A = new javax.swing.JLabel();
        lblMInitial_A = new javax.swing.JLabel();
        lblEmail_A = new javax.swing.JLabel();
        lblPassword_A = new javax.swing.JLabel();
        lblAddress1_A = new javax.swing.JLabel();
        lblAddress2_A = new javax.swing.JLabel();
        lblCity_A = new javax.swing.JLabel();
        lblState_A = new javax.swing.JLabel();
        lblZip_A = new javax.swing.JLabel();
        txtFirstName_A = new javax.swing.JTextField();
        txtMInitial_A = new javax.swing.JTextField();
        txtLastName_A = new javax.swing.JTextField();
        txtAddress1_A = new javax.swing.JTextField();
        txtAddress2_A = new javax.swing.JTextField();
        txtCity_A = new javax.swing.JTextField();
        txtState_A = new javax.swing.JTextField();
        txtZip_A = new javax.swing.JTextField();
        txtEmail_A = new javax.swing.JTextField();
        txtPassword_A = new javax.swing.JTextField();
        btnSubmit_A = new javax.swing.JButton();
        btnReset_A = new javax.swing.JButton();
        lblPhone_A = new javax.swing.JLabel();
        txtPhone_A = new javax.swing.JTextField();
        jPanel_B = new javax.swing.JPanel();
        lblFirstName1 = new javax.swing.JLabel();
        lblLastName1 = new javax.swing.JLabel();
        lblMInitial1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        lblAddress3 = new javax.swing.JLabel();
        lblAddress4 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        lblState1 = new javax.swing.JLabel();
        lblZip1 = new javax.swing.JLabel();
        txtFirstName1 = new javax.swing.JTextField();
        txtMInitial1 = new javax.swing.JTextField();
        txtLastName1 = new javax.swing.JTextField();
        txtAddress3 = new javax.swing.JTextField();
        txtAddress4 = new javax.swing.JTextField();
        txtCity1 = new javax.swing.JTextField();
        txtState1 = new javax.swing.JTextField();
        txtZip1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JTextField();
        btnSubmit2 = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Counter-Strike", 0, 24)); // NOI18N
        setSize(new java.awt.Dimension(1400, 800));

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel_A.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstName_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFirstName_A.setText("FIRST NAME:");

        lblLastName_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLastName_A.setText("LAST NAME:");

        lblMInitial_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMInitial_A.setText("MIDDLE INITIAL:");

        lblEmail_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEmail_A.setText("EMAIL:");

        lblPassword_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPassword_A.setText("PASSWORD:");

        lblAddress1_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAddress1_A.setText("ADDRESS 1:");

        lblAddress2_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAddress2_A.setText("ADDRESS 2:");

        lblCity_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCity_A.setText("CITY:");

        lblState_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblState_A.setText("STATE:");

        lblZip_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblZip_A.setText("ZIP:");

        btnSubmit_A.setText("Submit");
        btnSubmit_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit_AActionPerformed(evt);
            }
        });

        btnReset_A.setText("Reset");

        lblPhone_A.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPhone_A.setText("PHONE:");

        javax.swing.GroupLayout jPanel_ALayout = new javax.swing.GroupLayout(jPanel_A);
        jPanel_A.setLayout(jPanel_ALayout);
        jPanel_ALayout.setHorizontalGroup(
            jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ALayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblZip_A)
                    .addComponent(lblState_A)
                    .addComponent(lblCity_A)
                    .addComponent(lblAddress2_A)
                    .addComponent(lblAddress1_A)
                    .addComponent(lblMInitial_A)
                    .addComponent(lblFirstName_A)
                    .addComponent(lblLastName_A))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtState_A, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_ALayout.createSequentialGroup()
                        .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMInitial_A, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName_A)
                            .addComponent(txtAddress1_A)
                            .addComponent(txtAddress2_A)
                            .addComponent(txtCity_A, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtFirstName_A))
                        .addGap(197, 197, 197)
                        .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ALayout.createSequentialGroup()
                                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword_A)
                                    .addComponent(lblEmail_A)
                                    .addComponent(lblPhone_A))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail_A)
                                    .addComponent(txtPassword_A, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(txtPhone_A, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_ALayout.createSequentialGroup()
                                .addComponent(btnSubmit_A, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnReset_A, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtZip_A, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel_ALayout.setVerticalGroup(
            jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ALayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName_A)
                    .addComponent(lblEmail_A)
                    .addComponent(txtFirstName_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMInitial_A)
                    .addComponent(lblPassword_A)
                    .addComponent(txtMInitial_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName_A)
                    .addComponent(txtLastName_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone_A)
                    .addComponent(txtPhone_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1_A)
                    .addComponent(txtAddress1_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress2_A)
                    .addComponent(txtAddress2_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity_A)
                    .addComponent(txtCity_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit_A, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset_A, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState_A)
                    .addComponent(txtState_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZip_A)
                    .addComponent(txtZip_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD CUSTOMER", jPanel_A);

        jPanel_B.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstName1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFirstName1.setText("FIRST NAME:");

        lblLastName1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLastName1.setText("LAST NAME:");

        lblMInitial1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMInitial1.setText("MIDDLE INITIAL:");

        lblEmail1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEmail1.setText("EMAIL:");

        lblPassword1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPassword1.setText("PASSWORD:");

        lblAddress3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAddress3.setText("ADDRESS 1:");

        lblAddress4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblAddress4.setText("ADDRESS 2:");

        lblCity1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCity1.setText("CITY:");

        lblState1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblState1.setText("STATE:");

        lblZip1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblZip1.setText("ZIP:");

        btnSubmit2.setText("Submit");
        btnSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit2ActionPerformed(evt);
            }
        });

        btnReset2.setText("Reset");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("PHONE:");

        jTextField2.setText("jTextField1");

        javax.swing.GroupLayout jPanel_BLayout = new javax.swing.GroupLayout(jPanel_B);
        jPanel_B.setLayout(jPanel_BLayout);
        jPanel_BLayout.setHorizontalGroup(
            jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblZip1)
                    .addComponent(lblState1)
                    .addComponent(lblCity1)
                    .addComponent(lblAddress4)
                    .addComponent(lblAddress3)
                    .addComponent(lblMInitial1)
                    .addComponent(lblFirstName1)
                    .addComponent(lblLastName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_BLayout.createSequentialGroup()
                        .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMInitial1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName1)
                            .addComponent(txtAddress3)
                            .addComponent(txtAddress4)
                            .addComponent(txtCity1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtFirstName1))
                        .addGap(197, 197, 197)
                        .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_BLayout.createSequentialGroup()
                                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword1)
                                    .addComponent(lblEmail1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail1)
                                    .addComponent(txtPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_BLayout.createSequentialGroup()
                                .addComponent(btnSubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtZip1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel_BLayout.setVerticalGroup(
            jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName1)
                    .addComponent(lblEmail1)
                    .addComponent(txtFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMInitial1)
                    .addComponent(lblPassword1)
                    .addComponent(txtMInitial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName1)
                    .addComponent(txtLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress3)
                    .addComponent(txtAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress4)
                    .addComponent(txtAddress4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState1)
                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZip1)
                    .addComponent(txtZip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD GROOMER", jPanel_B);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmit_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit_AActionPerformed

    private void btnSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerServiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnReset_A;
    private javax.swing.JButton btnSubmit2;
    private javax.swing.JButton btnSubmit_A;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_A;
    private javax.swing.JPanel jPanel_B;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAddress1_A;
    private javax.swing.JLabel lblAddress2_A;
    private javax.swing.JLabel lblAddress3;
    private javax.swing.JLabel lblAddress4;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCity_A;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail_A;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblFirstName_A;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblLastName_A;
    private javax.swing.JLabel lblMInitial1;
    private javax.swing.JLabel lblMInitial_A;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPassword_A;
    private javax.swing.JLabel lblPhone_A;
    private javax.swing.JLabel lblState1;
    private javax.swing.JLabel lblState_A;
    private javax.swing.JLabel lblZip1;
    private javax.swing.JLabel lblZip_A;
    private javax.swing.JTextField txtAddress1_A;
    private javax.swing.JTextField txtAddress2_A;
    private javax.swing.JTextField txtAddress3;
    private javax.swing.JTextField txtAddress4;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtCity_A;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEmail_A;
    private javax.swing.JTextField txtFirstName1;
    private javax.swing.JTextField txtFirstName_A;
    private javax.swing.JTextField txtLastName1;
    private javax.swing.JTextField txtLastName_A;
    private javax.swing.JTextField txtMInitial1;
    private javax.swing.JTextField txtMInitial_A;
    private javax.swing.JTextField txtPassword2;
    private javax.swing.JTextField txtPassword_A;
    private javax.swing.JTextField txtPhone_A;
    private javax.swing.JTextField txtState1;
    private javax.swing.JTextField txtState_A;
    private javax.swing.JTextField txtZip1;
    private javax.swing.JTextField txtZip_A;
    // End of variables declaration//GEN-END:variables
}
